### ISSUE TITLE
[charm_tracing] If the buffer file can't be created, charm shouldn't fail

### ISSUE THREAD

**Issue by mmkay** [canonical/tempo-coordinator-k8s-operator#73]
### Enhancement Proposal

There might be cases where the buffer file cannot be created: such as a restricted environment that won't allow you to create new files. In this case, the charm shouldn't error out.

**Comment by PietroPasotti** [comment]
The code already guards against Exceptions bubbling up from that whole codepath, so I think this is already the case. Closing until we have an indication that this is what in fact is happening.
