### ISSUE TITLE
Fix ReceiverProtocols confusion

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/tempo-coordinator-k8s-operator#8]
in that case we have some confusion in the types and enums around the code that we NEED to fix. See the ReceiverProtocol enum

_Originally posted by @PietroPasotti in https://github.com/canonical/tempo-coordinator-k8s-operator/pull/7#discussion_r1660908400_

**Comment by PietroPasotti** [comment]
task breakdown:

- verify what the actual possible configuration options for the receivers block can be. 
  Can we put in there any one of the contrib receivers as listed in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main ? 
- Decide on a list of protocols we want to enable
- adjust force-enable options accordingly
- adjust tracing charm lib (the ReceiverProtocols enum) and document clearly our choice next to it
  - no changes should be necessary for tempo-cluster
- adjust receiver ports in https://github.com/canonical/tempo-coordinator-k8s-operator/blob/main/src/tempo.py#L49
- propagate this change down to grafana-agent

**Comment by michaeldmitry** [comment]
List of Tempo's supported protocols: kafka, jaeger, zipkin, opencensus, otlp

Reference:
https://github.com/grafana/tempo/blob/main/modules/distributor/receiver/shim.go#L163C2-L169C3
![image](https://github.com/canonical/tempo-coordinator-k8s-operator/assets/33381599/6b872924-e8eb-4e9c-8a17-4850638ad604)

**Comment by michaeldmitry** [comment]
ADR:
https://github.com/canonical/observability/pull/196

Fixed by:
https://github.com/canonical/tempo-worker-k8s-operator/pull/11
https://github.com/canonical/tempo-coordinator-k8s-operator/pull/13
https://github.com/canonical/tempo-k8s-operator/pull/149
